// flow-typed signature: 3b5f08289684758193fcf66ca169d1b4
// flow-typed version: <<STUB>>/parcel_v^1.9.7/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'parcel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'parcel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'parcel/bin/cli' {
  declare module.exports: any;
}

declare module 'parcel/lib/Asset' {
  declare module.exports: any;
}

declare module 'parcel/lib/assets/CoffeeScriptAsset' {
  declare module.exports: any;
}

declare module 'parcel/lib/assets/CSSAsset' {
  declare module.exports: any;
}

declare module 'parcel/lib/assets/GlobAsset' {
  declare module.exports: any;
}

declare module 'parcel/lib/assets/GLSLAsset' {
  declare module.exports: any;
}

declare module 'parcel/lib/assets/GraphqlAsset' {
  declare module.exports: any;
}

declare module 'parcel/lib/assets/HTMLAsset' {
  declare module.exports: any;
}

declare module 'parcel/lib/assets/JSAsset' {
  declare module.exports: any;
}

declare module 'parcel/lib/assets/JSONAsset' {
  declare module.exports: any;
}

declare module 'parcel/lib/assets/LESSAsset' {
  declare module.exports: any;
}

declare module 'parcel/lib/assets/PugAsset' {
  declare module.exports: any;
}

declare module 'parcel/lib/assets/RawAsset' {
  declare module.exports: any;
}

declare module 'parcel/lib/assets/ReasonAsset' {
  declare module.exports: any;
}

declare module 'parcel/lib/assets/RustAsset' {
  declare module.exports: any;
}

declare module 'parcel/lib/assets/SASSAsset' {
  declare module.exports: any;
}

declare module 'parcel/lib/assets/StylusAsset' {
  declare module.exports: any;
}

declare module 'parcel/lib/assets/TOMLAsset' {
  declare module.exports: any;
}

declare module 'parcel/lib/assets/TypeScriptAsset' {
  declare module.exports: any;
}

declare module 'parcel/lib/assets/VueAsset' {
  declare module.exports: any;
}

declare module 'parcel/lib/assets/WebManifestAsset' {
  declare module.exports: any;
}

declare module 'parcel/lib/assets/YAMLAsset' {
  declare module.exports: any;
}

declare module 'parcel/lib/builtins/_empty' {
  declare module.exports: any;
}

declare module 'parcel/lib/builtins/bundle-loader' {
  declare module.exports: any;
}

declare module 'parcel/lib/builtins/bundle-url' {
  declare module.exports: any;
}

declare module 'parcel/lib/builtins/css-loader' {
  declare module.exports: any;
}

declare module 'parcel/lib/builtins/helpers' {
  declare module.exports: any;
}

declare module 'parcel/lib/builtins/hmr-runtime' {
  declare module.exports: any;
}

declare module 'parcel/lib/builtins/index' {
  declare module.exports: any;
}

declare module 'parcel/lib/builtins/loaders/browser/css-loader' {
  declare module.exports: any;
}

declare module 'parcel/lib/builtins/loaders/browser/js-loader' {
  declare module.exports: any;
}

declare module 'parcel/lib/builtins/loaders/browser/wasm-loader' {
  declare module.exports: any;
}

declare module 'parcel/lib/builtins/loaders/node/css-loader' {
  declare module.exports: any;
}

declare module 'parcel/lib/builtins/loaders/node/js-loader' {
  declare module.exports: any;
}

declare module 'parcel/lib/builtins/loaders/node/wasm-loader' {
  declare module.exports: any;
}

declare module 'parcel/lib/builtins/prelude' {
  declare module.exports: any;
}

declare module 'parcel/lib/builtins/prelude.min' {
  declare module.exports: any;
}

declare module 'parcel/lib/builtins/prelude2' {
  declare module.exports: any;
}

declare module 'parcel/lib/builtins/prelude2.min' {
  declare module.exports: any;
}

declare module 'parcel/lib/Bundle' {
  declare module.exports: any;
}

declare module 'parcel/lib/Bundler' {
  declare module.exports: any;
}

declare module 'parcel/lib/cli' {
  declare module.exports: any;
}

declare module 'parcel/lib/FSCache' {
  declare module.exports: any;
}

declare module 'parcel/lib/HMRServer' {
  declare module.exports: any;
}

declare module 'parcel/lib/Logger' {
  declare module.exports: any;
}

declare module 'parcel/lib/packagers/CSSPackager' {
  declare module.exports: any;
}

declare module 'parcel/lib/packagers/HTMLPackager' {
  declare module.exports: any;
}

declare module 'parcel/lib/packagers/index' {
  declare module.exports: any;
}

declare module 'parcel/lib/packagers/JSConcatPackager' {
  declare module.exports: any;
}

declare module 'parcel/lib/packagers/JSPackager' {
  declare module.exports: any;
}

declare module 'parcel/lib/packagers/Packager' {
  declare module.exports: any;
}

declare module 'parcel/lib/packagers/RawPackager' {
  declare module.exports: any;
}

declare module 'parcel/lib/packagers/SourceMapPackager' {
  declare module.exports: any;
}

declare module 'parcel/lib/Parser' {
  declare module.exports: any;
}

declare module 'parcel/lib/Pipeline' {
  declare module.exports: any;
}

declare module 'parcel/lib/Resolver' {
  declare module.exports: any;
}

declare module 'parcel/lib/scope-hoisting/concat' {
  declare module.exports: any;
}

declare module 'parcel/lib/scope-hoisting/hoist' {
  declare module.exports: any;
}

declare module 'parcel/lib/scope-hoisting/mangler' {
  declare module.exports: any;
}

declare module 'parcel/lib/scope-hoisting/renamer' {
  declare module.exports: any;
}

declare module 'parcel/lib/scope-hoisting/shake' {
  declare module.exports: any;
}

declare module 'parcel/lib/scope-hoisting/utils' {
  declare module.exports: any;
}

declare module 'parcel/lib/Server' {
  declare module.exports: any;
}

declare module 'parcel/lib/SourceMap' {
  declare module.exports: any;
}

declare module 'parcel/lib/transforms/babel' {
  declare module.exports: any;
}

declare module 'parcel/lib/transforms/htmlnano' {
  declare module.exports: any;
}

declare module 'parcel/lib/transforms/postcss' {
  declare module.exports: any;
}

declare module 'parcel/lib/transforms/posthtml' {
  declare module.exports: any;
}

declare module 'parcel/lib/transforms/terser' {
  declare module.exports: any;
}

declare module 'parcel/lib/utils/bundleReport' {
  declare module.exports: any;
}

declare module 'parcel/lib/utils/config' {
  declare module.exports: any;
}

declare module 'parcel/lib/utils/customErrors' {
  declare module.exports: any;
}

declare module 'parcel/lib/utils/emoji' {
  declare module.exports: any;
}

declare module 'parcel/lib/utils/env' {
  declare module.exports: any;
}

declare module 'parcel/lib/utils/fs' {
  declare module.exports: any;
}

declare module 'parcel/lib/utils/generateCertificate' {
  declare module.exports: any;
}

declare module 'parcel/lib/utils/getCertificate' {
  declare module.exports: any;
}

declare module 'parcel/lib/utils/getRootDir' {
  declare module.exports: any;
}

declare module 'parcel/lib/utils/getTargetEngines' {
  declare module.exports: any;
}

declare module 'parcel/lib/utils/installPackage' {
  declare module.exports: any;
}

declare module 'parcel/lib/utils/is-url' {
  declare module.exports: any;
}

declare module 'parcel/lib/utils/lineCounter' {
  declare module.exports: any;
}

declare module 'parcel/lib/utils/loadPlugins' {
  declare module.exports: any;
}

declare module 'parcel/lib/utils/localRequire' {
  declare module.exports: any;
}

declare module 'parcel/lib/utils/md5' {
  declare module.exports: any;
}

declare module 'parcel/lib/utils/objectHash' {
  declare module.exports: any;
}

declare module 'parcel/lib/utils/openInBrowser' {
  declare module.exports: any;
}

declare module 'parcel/lib/utils/parseCSSImport' {
  declare module.exports: any;
}

declare module 'parcel/lib/utils/pipeSpawn' {
  declare module.exports: any;
}

declare module 'parcel/lib/utils/prettifyTime' {
  declare module.exports: any;
}

declare module 'parcel/lib/utils/prettyError' {
  declare module.exports: any;
}

declare module 'parcel/lib/utils/PromiseQueue' {
  declare module.exports: any;
}

declare module 'parcel/lib/utils/promisify' {
  declare module.exports: any;
}

declare module 'parcel/lib/utils/serializeObject' {
  declare module.exports: any;
}

declare module 'parcel/lib/utils/syncPromise' {
  declare module.exports: any;
}

declare module 'parcel/lib/utils/urlJoin' {
  declare module.exports: any;
}

declare module 'parcel/lib/visitors/dependencies' {
  declare module.exports: any;
}

declare module 'parcel/lib/visitors/env' {
  declare module.exports: any;
}

declare module 'parcel/lib/visitors/fs' {
  declare module.exports: any;
}

declare module 'parcel/lib/visitors/globals' {
  declare module.exports: any;
}

declare module 'parcel/lib/visitors/matches-pattern' {
  declare module.exports: any;
}

declare module 'parcel/lib/Watcher' {
  declare module.exports: any;
}

declare module 'parcel/lib/worker' {
  declare module.exports: any;
}

declare module 'parcel/lib/workerfarm/child' {
  declare module.exports: any;
}

declare module 'parcel/lib/workerfarm/errorUtils' {
  declare module.exports: any;
}

declare module 'parcel/lib/workerfarm/Worker' {
  declare module.exports: any;
}

declare module 'parcel/lib/workerfarm/WorkerFarm' {
  declare module.exports: any;
}

declare module 'parcel/src/Asset' {
  declare module.exports: any;
}

declare module 'parcel/src/assets/CoffeeScriptAsset' {
  declare module.exports: any;
}

declare module 'parcel/src/assets/CSSAsset' {
  declare module.exports: any;
}

declare module 'parcel/src/assets/GlobAsset' {
  declare module.exports: any;
}

declare module 'parcel/src/assets/GLSLAsset' {
  declare module.exports: any;
}

declare module 'parcel/src/assets/GraphqlAsset' {
  declare module.exports: any;
}

declare module 'parcel/src/assets/HTMLAsset' {
  declare module.exports: any;
}

declare module 'parcel/src/assets/JSAsset' {
  declare module.exports: any;
}

declare module 'parcel/src/assets/JSONAsset' {
  declare module.exports: any;
}

declare module 'parcel/src/assets/LESSAsset' {
  declare module.exports: any;
}

declare module 'parcel/src/assets/PugAsset' {
  declare module.exports: any;
}

declare module 'parcel/src/assets/RawAsset' {
  declare module.exports: any;
}

declare module 'parcel/src/assets/ReasonAsset' {
  declare module.exports: any;
}

declare module 'parcel/src/assets/RustAsset' {
  declare module.exports: any;
}

declare module 'parcel/src/assets/SASSAsset' {
  declare module.exports: any;
}

declare module 'parcel/src/assets/StylusAsset' {
  declare module.exports: any;
}

declare module 'parcel/src/assets/TOMLAsset' {
  declare module.exports: any;
}

declare module 'parcel/src/assets/TypeScriptAsset' {
  declare module.exports: any;
}

declare module 'parcel/src/assets/VueAsset' {
  declare module.exports: any;
}

declare module 'parcel/src/assets/WebManifestAsset' {
  declare module.exports: any;
}

declare module 'parcel/src/assets/YAMLAsset' {
  declare module.exports: any;
}

declare module 'parcel/src/builtins/_empty' {
  declare module.exports: any;
}

declare module 'parcel/src/builtins/bundle-loader' {
  declare module.exports: any;
}

declare module 'parcel/src/builtins/bundle-url' {
  declare module.exports: any;
}

declare module 'parcel/src/builtins/css-loader' {
  declare module.exports: any;
}

declare module 'parcel/src/builtins/helpers' {
  declare module.exports: any;
}

declare module 'parcel/src/builtins/hmr-runtime' {
  declare module.exports: any;
}

declare module 'parcel/src/builtins/index' {
  declare module.exports: any;
}

declare module 'parcel/src/builtins/loaders/browser/css-loader' {
  declare module.exports: any;
}

declare module 'parcel/src/builtins/loaders/browser/js-loader' {
  declare module.exports: any;
}

declare module 'parcel/src/builtins/loaders/browser/wasm-loader' {
  declare module.exports: any;
}

declare module 'parcel/src/builtins/loaders/node/css-loader' {
  declare module.exports: any;
}

declare module 'parcel/src/builtins/loaders/node/js-loader' {
  declare module.exports: any;
}

declare module 'parcel/src/builtins/loaders/node/wasm-loader' {
  declare module.exports: any;
}

declare module 'parcel/src/builtins/prelude' {
  declare module.exports: any;
}

declare module 'parcel/src/builtins/prelude.min' {
  declare module.exports: any;
}

declare module 'parcel/src/builtins/prelude2' {
  declare module.exports: any;
}

declare module 'parcel/src/builtins/prelude2.min' {
  declare module.exports: any;
}

declare module 'parcel/src/Bundle' {
  declare module.exports: any;
}

declare module 'parcel/src/Bundler' {
  declare module.exports: any;
}

declare module 'parcel/src/cli' {
  declare module.exports: any;
}

declare module 'parcel/src/FSCache' {
  declare module.exports: any;
}

declare module 'parcel/src/HMRServer' {
  declare module.exports: any;
}

declare module 'parcel/src/Logger' {
  declare module.exports: any;
}

declare module 'parcel/src/packagers/CSSPackager' {
  declare module.exports: any;
}

declare module 'parcel/src/packagers/HTMLPackager' {
  declare module.exports: any;
}

declare module 'parcel/src/packagers/index' {
  declare module.exports: any;
}

declare module 'parcel/src/packagers/JSConcatPackager' {
  declare module.exports: any;
}

declare module 'parcel/src/packagers/JSPackager' {
  declare module.exports: any;
}

declare module 'parcel/src/packagers/Packager' {
  declare module.exports: any;
}

declare module 'parcel/src/packagers/RawPackager' {
  declare module.exports: any;
}

declare module 'parcel/src/packagers/SourceMapPackager' {
  declare module.exports: any;
}

declare module 'parcel/src/Parser' {
  declare module.exports: any;
}

declare module 'parcel/src/Pipeline' {
  declare module.exports: any;
}

declare module 'parcel/src/Resolver' {
  declare module.exports: any;
}

declare module 'parcel/src/scope-hoisting/concat' {
  declare module.exports: any;
}

declare module 'parcel/src/scope-hoisting/hoist' {
  declare module.exports: any;
}

declare module 'parcel/src/scope-hoisting/mangler' {
  declare module.exports: any;
}

declare module 'parcel/src/scope-hoisting/renamer' {
  declare module.exports: any;
}

declare module 'parcel/src/scope-hoisting/shake' {
  declare module.exports: any;
}

declare module 'parcel/src/scope-hoisting/utils' {
  declare module.exports: any;
}

declare module 'parcel/src/Server' {
  declare module.exports: any;
}

declare module 'parcel/src/SourceMap' {
  declare module.exports: any;
}

declare module 'parcel/src/transforms/babel' {
  declare module.exports: any;
}

declare module 'parcel/src/transforms/htmlnano' {
  declare module.exports: any;
}

declare module 'parcel/src/transforms/postcss' {
  declare module.exports: any;
}

declare module 'parcel/src/transforms/posthtml' {
  declare module.exports: any;
}

declare module 'parcel/src/transforms/terser' {
  declare module.exports: any;
}

declare module 'parcel/src/utils/bundleReport' {
  declare module.exports: any;
}

declare module 'parcel/src/utils/config' {
  declare module.exports: any;
}

declare module 'parcel/src/utils/customErrors' {
  declare module.exports: any;
}

declare module 'parcel/src/utils/emoji' {
  declare module.exports: any;
}

declare module 'parcel/src/utils/env' {
  declare module.exports: any;
}

declare module 'parcel/src/utils/fs' {
  declare module.exports: any;
}

declare module 'parcel/src/utils/generateCertificate' {
  declare module.exports: any;
}

declare module 'parcel/src/utils/getCertificate' {
  declare module.exports: any;
}

declare module 'parcel/src/utils/getRootDir' {
  declare module.exports: any;
}

declare module 'parcel/src/utils/getTargetEngines' {
  declare module.exports: any;
}

declare module 'parcel/src/utils/installPackage' {
  declare module.exports: any;
}

declare module 'parcel/src/utils/is-url' {
  declare module.exports: any;
}

declare module 'parcel/src/utils/lineCounter' {
  declare module.exports: any;
}

declare module 'parcel/src/utils/loadPlugins' {
  declare module.exports: any;
}

declare module 'parcel/src/utils/localRequire' {
  declare module.exports: any;
}

declare module 'parcel/src/utils/md5' {
  declare module.exports: any;
}

declare module 'parcel/src/utils/objectHash' {
  declare module.exports: any;
}

declare module 'parcel/src/utils/openInBrowser' {
  declare module.exports: any;
}

declare module 'parcel/src/utils/parseCSSImport' {
  declare module.exports: any;
}

declare module 'parcel/src/utils/pipeSpawn' {
  declare module.exports: any;
}

declare module 'parcel/src/utils/prettifyTime' {
  declare module.exports: any;
}

declare module 'parcel/src/utils/prettyError' {
  declare module.exports: any;
}

declare module 'parcel/src/utils/PromiseQueue' {
  declare module.exports: any;
}

declare module 'parcel/src/utils/promisify' {
  declare module.exports: any;
}

declare module 'parcel/src/utils/serializeObject' {
  declare module.exports: any;
}

declare module 'parcel/src/utils/syncPromise' {
  declare module.exports: any;
}

declare module 'parcel/src/utils/urlJoin' {
  declare module.exports: any;
}

declare module 'parcel/src/visitors/dependencies' {
  declare module.exports: any;
}

declare module 'parcel/src/visitors/env' {
  declare module.exports: any;
}

declare module 'parcel/src/visitors/fs' {
  declare module.exports: any;
}

declare module 'parcel/src/visitors/globals' {
  declare module.exports: any;
}

declare module 'parcel/src/visitors/matches-pattern' {
  declare module.exports: any;
}

declare module 'parcel/src/Watcher' {
  declare module.exports: any;
}

declare module 'parcel/src/worker' {
  declare module.exports: any;
}

declare module 'parcel/src/workerfarm/child' {
  declare module.exports: any;
}

declare module 'parcel/src/workerfarm/errorUtils' {
  declare module.exports: any;
}

declare module 'parcel/src/workerfarm/Worker' {
  declare module.exports: any;
}

declare module 'parcel/src/workerfarm/WorkerFarm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'parcel/bin/cli.js' {
  declare module.exports: $Exports<'parcel/bin/cli'>;
}
declare module 'parcel/index' {
  declare module.exports: $Exports<'parcel'>;
}
declare module 'parcel/index.js' {
  declare module.exports: $Exports<'parcel'>;
}
declare module 'parcel/lib/Asset.js' {
  declare module.exports: $Exports<'parcel/lib/Asset'>;
}
declare module 'parcel/lib/assets/CoffeeScriptAsset.js' {
  declare module.exports: $Exports<'parcel/lib/assets/CoffeeScriptAsset'>;
}
declare module 'parcel/lib/assets/CSSAsset.js' {
  declare module.exports: $Exports<'parcel/lib/assets/CSSAsset'>;
}
declare module 'parcel/lib/assets/GlobAsset.js' {
  declare module.exports: $Exports<'parcel/lib/assets/GlobAsset'>;
}
declare module 'parcel/lib/assets/GLSLAsset.js' {
  declare module.exports: $Exports<'parcel/lib/assets/GLSLAsset'>;
}
declare module 'parcel/lib/assets/GraphqlAsset.js' {
  declare module.exports: $Exports<'parcel/lib/assets/GraphqlAsset'>;
}
declare module 'parcel/lib/assets/HTMLAsset.js' {
  declare module.exports: $Exports<'parcel/lib/assets/HTMLAsset'>;
}
declare module 'parcel/lib/assets/JSAsset.js' {
  declare module.exports: $Exports<'parcel/lib/assets/JSAsset'>;
}
declare module 'parcel/lib/assets/JSONAsset.js' {
  declare module.exports: $Exports<'parcel/lib/assets/JSONAsset'>;
}
declare module 'parcel/lib/assets/LESSAsset.js' {
  declare module.exports: $Exports<'parcel/lib/assets/LESSAsset'>;
}
declare module 'parcel/lib/assets/PugAsset.js' {
  declare module.exports: $Exports<'parcel/lib/assets/PugAsset'>;
}
declare module 'parcel/lib/assets/RawAsset.js' {
  declare module.exports: $Exports<'parcel/lib/assets/RawAsset'>;
}
declare module 'parcel/lib/assets/ReasonAsset.js' {
  declare module.exports: $Exports<'parcel/lib/assets/ReasonAsset'>;
}
declare module 'parcel/lib/assets/RustAsset.js' {
  declare module.exports: $Exports<'parcel/lib/assets/RustAsset'>;
}
declare module 'parcel/lib/assets/SASSAsset.js' {
  declare module.exports: $Exports<'parcel/lib/assets/SASSAsset'>;
}
declare module 'parcel/lib/assets/StylusAsset.js' {
  declare module.exports: $Exports<'parcel/lib/assets/StylusAsset'>;
}
declare module 'parcel/lib/assets/TOMLAsset.js' {
  declare module.exports: $Exports<'parcel/lib/assets/TOMLAsset'>;
}
declare module 'parcel/lib/assets/TypeScriptAsset.js' {
  declare module.exports: $Exports<'parcel/lib/assets/TypeScriptAsset'>;
}
declare module 'parcel/lib/assets/VueAsset.js' {
  declare module.exports: $Exports<'parcel/lib/assets/VueAsset'>;
}
declare module 'parcel/lib/assets/WebManifestAsset.js' {
  declare module.exports: $Exports<'parcel/lib/assets/WebManifestAsset'>;
}
declare module 'parcel/lib/assets/YAMLAsset.js' {
  declare module.exports: $Exports<'parcel/lib/assets/YAMLAsset'>;
}
declare module 'parcel/lib/builtins/_empty.js' {
  declare module.exports: $Exports<'parcel/lib/builtins/_empty'>;
}
declare module 'parcel/lib/builtins/bundle-loader.js' {
  declare module.exports: $Exports<'parcel/lib/builtins/bundle-loader'>;
}
declare module 'parcel/lib/builtins/bundle-url.js' {
  declare module.exports: $Exports<'parcel/lib/builtins/bundle-url'>;
}
declare module 'parcel/lib/builtins/css-loader.js' {
  declare module.exports: $Exports<'parcel/lib/builtins/css-loader'>;
}
declare module 'parcel/lib/builtins/helpers.js' {
  declare module.exports: $Exports<'parcel/lib/builtins/helpers'>;
}
declare module 'parcel/lib/builtins/hmr-runtime.js' {
  declare module.exports: $Exports<'parcel/lib/builtins/hmr-runtime'>;
}
declare module 'parcel/lib/builtins/index.js' {
  declare module.exports: $Exports<'parcel/lib/builtins/index'>;
}
declare module 'parcel/lib/builtins/loaders/browser/css-loader.js' {
  declare module.exports: $Exports<'parcel/lib/builtins/loaders/browser/css-loader'>;
}
declare module 'parcel/lib/builtins/loaders/browser/js-loader.js' {
  declare module.exports: $Exports<'parcel/lib/builtins/loaders/browser/js-loader'>;
}
declare module 'parcel/lib/builtins/loaders/browser/wasm-loader.js' {
  declare module.exports: $Exports<'parcel/lib/builtins/loaders/browser/wasm-loader'>;
}
declare module 'parcel/lib/builtins/loaders/node/css-loader.js' {
  declare module.exports: $Exports<'parcel/lib/builtins/loaders/node/css-loader'>;
}
declare module 'parcel/lib/builtins/loaders/node/js-loader.js' {
  declare module.exports: $Exports<'parcel/lib/builtins/loaders/node/js-loader'>;
}
declare module 'parcel/lib/builtins/loaders/node/wasm-loader.js' {
  declare module.exports: $Exports<'parcel/lib/builtins/loaders/node/wasm-loader'>;
}
declare module 'parcel/lib/builtins/prelude.js' {
  declare module.exports: $Exports<'parcel/lib/builtins/prelude'>;
}
declare module 'parcel/lib/builtins/prelude.min.js' {
  declare module.exports: $Exports<'parcel/lib/builtins/prelude.min'>;
}
declare module 'parcel/lib/builtins/prelude2.js' {
  declare module.exports: $Exports<'parcel/lib/builtins/prelude2'>;
}
declare module 'parcel/lib/builtins/prelude2.min.js' {
  declare module.exports: $Exports<'parcel/lib/builtins/prelude2.min'>;
}
declare module 'parcel/lib/Bundle.js' {
  declare module.exports: $Exports<'parcel/lib/Bundle'>;
}
declare module 'parcel/lib/Bundler.js' {
  declare module.exports: $Exports<'parcel/lib/Bundler'>;
}
declare module 'parcel/lib/cli.js' {
  declare module.exports: $Exports<'parcel/lib/cli'>;
}
declare module 'parcel/lib/FSCache.js' {
  declare module.exports: $Exports<'parcel/lib/FSCache'>;
}
declare module 'parcel/lib/HMRServer.js' {
  declare module.exports: $Exports<'parcel/lib/HMRServer'>;
}
declare module 'parcel/lib/Logger.js' {
  declare module.exports: $Exports<'parcel/lib/Logger'>;
}
declare module 'parcel/lib/packagers/CSSPackager.js' {
  declare module.exports: $Exports<'parcel/lib/packagers/CSSPackager'>;
}
declare module 'parcel/lib/packagers/HTMLPackager.js' {
  declare module.exports: $Exports<'parcel/lib/packagers/HTMLPackager'>;
}
declare module 'parcel/lib/packagers/index.js' {
  declare module.exports: $Exports<'parcel/lib/packagers/index'>;
}
declare module 'parcel/lib/packagers/JSConcatPackager.js' {
  declare module.exports: $Exports<'parcel/lib/packagers/JSConcatPackager'>;
}
declare module 'parcel/lib/packagers/JSPackager.js' {
  declare module.exports: $Exports<'parcel/lib/packagers/JSPackager'>;
}
declare module 'parcel/lib/packagers/Packager.js' {
  declare module.exports: $Exports<'parcel/lib/packagers/Packager'>;
}
declare module 'parcel/lib/packagers/RawPackager.js' {
  declare module.exports: $Exports<'parcel/lib/packagers/RawPackager'>;
}
declare module 'parcel/lib/packagers/SourceMapPackager.js' {
  declare module.exports: $Exports<'parcel/lib/packagers/SourceMapPackager'>;
}
declare module 'parcel/lib/Parser.js' {
  declare module.exports: $Exports<'parcel/lib/Parser'>;
}
declare module 'parcel/lib/Pipeline.js' {
  declare module.exports: $Exports<'parcel/lib/Pipeline'>;
}
declare module 'parcel/lib/Resolver.js' {
  declare module.exports: $Exports<'parcel/lib/Resolver'>;
}
declare module 'parcel/lib/scope-hoisting/concat.js' {
  declare module.exports: $Exports<'parcel/lib/scope-hoisting/concat'>;
}
declare module 'parcel/lib/scope-hoisting/hoist.js' {
  declare module.exports: $Exports<'parcel/lib/scope-hoisting/hoist'>;
}
declare module 'parcel/lib/scope-hoisting/mangler.js' {
  declare module.exports: $Exports<'parcel/lib/scope-hoisting/mangler'>;
}
declare module 'parcel/lib/scope-hoisting/renamer.js' {
  declare module.exports: $Exports<'parcel/lib/scope-hoisting/renamer'>;
}
declare module 'parcel/lib/scope-hoisting/shake.js' {
  declare module.exports: $Exports<'parcel/lib/scope-hoisting/shake'>;
}
declare module 'parcel/lib/scope-hoisting/utils.js' {
  declare module.exports: $Exports<'parcel/lib/scope-hoisting/utils'>;
}
declare module 'parcel/lib/Server.js' {
  declare module.exports: $Exports<'parcel/lib/Server'>;
}
declare module 'parcel/lib/SourceMap.js' {
  declare module.exports: $Exports<'parcel/lib/SourceMap'>;
}
declare module 'parcel/lib/transforms/babel.js' {
  declare module.exports: $Exports<'parcel/lib/transforms/babel'>;
}
declare module 'parcel/lib/transforms/htmlnano.js' {
  declare module.exports: $Exports<'parcel/lib/transforms/htmlnano'>;
}
declare module 'parcel/lib/transforms/postcss.js' {
  declare module.exports: $Exports<'parcel/lib/transforms/postcss'>;
}
declare module 'parcel/lib/transforms/posthtml.js' {
  declare module.exports: $Exports<'parcel/lib/transforms/posthtml'>;
}
declare module 'parcel/lib/transforms/terser.js' {
  declare module.exports: $Exports<'parcel/lib/transforms/terser'>;
}
declare module 'parcel/lib/utils/bundleReport.js' {
  declare module.exports: $Exports<'parcel/lib/utils/bundleReport'>;
}
declare module 'parcel/lib/utils/config.js' {
  declare module.exports: $Exports<'parcel/lib/utils/config'>;
}
declare module 'parcel/lib/utils/customErrors.js' {
  declare module.exports: $Exports<'parcel/lib/utils/customErrors'>;
}
declare module 'parcel/lib/utils/emoji.js' {
  declare module.exports: $Exports<'parcel/lib/utils/emoji'>;
}
declare module 'parcel/lib/utils/env.js' {
  declare module.exports: $Exports<'parcel/lib/utils/env'>;
}
declare module 'parcel/lib/utils/fs.js' {
  declare module.exports: $Exports<'parcel/lib/utils/fs'>;
}
declare module 'parcel/lib/utils/generateCertificate.js' {
  declare module.exports: $Exports<'parcel/lib/utils/generateCertificate'>;
}
declare module 'parcel/lib/utils/getCertificate.js' {
  declare module.exports: $Exports<'parcel/lib/utils/getCertificate'>;
}
declare module 'parcel/lib/utils/getRootDir.js' {
  declare module.exports: $Exports<'parcel/lib/utils/getRootDir'>;
}
declare module 'parcel/lib/utils/getTargetEngines.js' {
  declare module.exports: $Exports<'parcel/lib/utils/getTargetEngines'>;
}
declare module 'parcel/lib/utils/installPackage.js' {
  declare module.exports: $Exports<'parcel/lib/utils/installPackage'>;
}
declare module 'parcel/lib/utils/is-url.js' {
  declare module.exports: $Exports<'parcel/lib/utils/is-url'>;
}
declare module 'parcel/lib/utils/lineCounter.js' {
  declare module.exports: $Exports<'parcel/lib/utils/lineCounter'>;
}
declare module 'parcel/lib/utils/loadPlugins.js' {
  declare module.exports: $Exports<'parcel/lib/utils/loadPlugins'>;
}
declare module 'parcel/lib/utils/localRequire.js' {
  declare module.exports: $Exports<'parcel/lib/utils/localRequire'>;
}
declare module 'parcel/lib/utils/md5.js' {
  declare module.exports: $Exports<'parcel/lib/utils/md5'>;
}
declare module 'parcel/lib/utils/objectHash.js' {
  declare module.exports: $Exports<'parcel/lib/utils/objectHash'>;
}
declare module 'parcel/lib/utils/openInBrowser.js' {
  declare module.exports: $Exports<'parcel/lib/utils/openInBrowser'>;
}
declare module 'parcel/lib/utils/parseCSSImport.js' {
  declare module.exports: $Exports<'parcel/lib/utils/parseCSSImport'>;
}
declare module 'parcel/lib/utils/pipeSpawn.js' {
  declare module.exports: $Exports<'parcel/lib/utils/pipeSpawn'>;
}
declare module 'parcel/lib/utils/prettifyTime.js' {
  declare module.exports: $Exports<'parcel/lib/utils/prettifyTime'>;
}
declare module 'parcel/lib/utils/prettyError.js' {
  declare module.exports: $Exports<'parcel/lib/utils/prettyError'>;
}
declare module 'parcel/lib/utils/PromiseQueue.js' {
  declare module.exports: $Exports<'parcel/lib/utils/PromiseQueue'>;
}
declare module 'parcel/lib/utils/promisify.js' {
  declare module.exports: $Exports<'parcel/lib/utils/promisify'>;
}
declare module 'parcel/lib/utils/serializeObject.js' {
  declare module.exports: $Exports<'parcel/lib/utils/serializeObject'>;
}
declare module 'parcel/lib/utils/syncPromise.js' {
  declare module.exports: $Exports<'parcel/lib/utils/syncPromise'>;
}
declare module 'parcel/lib/utils/urlJoin.js' {
  declare module.exports: $Exports<'parcel/lib/utils/urlJoin'>;
}
declare module 'parcel/lib/visitors/dependencies.js' {
  declare module.exports: $Exports<'parcel/lib/visitors/dependencies'>;
}
declare module 'parcel/lib/visitors/env.js' {
  declare module.exports: $Exports<'parcel/lib/visitors/env'>;
}
declare module 'parcel/lib/visitors/fs.js' {
  declare module.exports: $Exports<'parcel/lib/visitors/fs'>;
}
declare module 'parcel/lib/visitors/globals.js' {
  declare module.exports: $Exports<'parcel/lib/visitors/globals'>;
}
declare module 'parcel/lib/visitors/matches-pattern.js' {
  declare module.exports: $Exports<'parcel/lib/visitors/matches-pattern'>;
}
declare module 'parcel/lib/Watcher.js' {
  declare module.exports: $Exports<'parcel/lib/Watcher'>;
}
declare module 'parcel/lib/worker.js' {
  declare module.exports: $Exports<'parcel/lib/worker'>;
}
declare module 'parcel/lib/workerfarm/child.js' {
  declare module.exports: $Exports<'parcel/lib/workerfarm/child'>;
}
declare module 'parcel/lib/workerfarm/errorUtils.js' {
  declare module.exports: $Exports<'parcel/lib/workerfarm/errorUtils'>;
}
declare module 'parcel/lib/workerfarm/Worker.js' {
  declare module.exports: $Exports<'parcel/lib/workerfarm/Worker'>;
}
declare module 'parcel/lib/workerfarm/WorkerFarm.js' {
  declare module.exports: $Exports<'parcel/lib/workerfarm/WorkerFarm'>;
}
declare module 'parcel/src/Asset.js' {
  declare module.exports: $Exports<'parcel/src/Asset'>;
}
declare module 'parcel/src/assets/CoffeeScriptAsset.js' {
  declare module.exports: $Exports<'parcel/src/assets/CoffeeScriptAsset'>;
}
declare module 'parcel/src/assets/CSSAsset.js' {
  declare module.exports: $Exports<'parcel/src/assets/CSSAsset'>;
}
declare module 'parcel/src/assets/GlobAsset.js' {
  declare module.exports: $Exports<'parcel/src/assets/GlobAsset'>;
}
declare module 'parcel/src/assets/GLSLAsset.js' {
  declare module.exports: $Exports<'parcel/src/assets/GLSLAsset'>;
}
declare module 'parcel/src/assets/GraphqlAsset.js' {
  declare module.exports: $Exports<'parcel/src/assets/GraphqlAsset'>;
}
declare module 'parcel/src/assets/HTMLAsset.js' {
  declare module.exports: $Exports<'parcel/src/assets/HTMLAsset'>;
}
declare module 'parcel/src/assets/JSAsset.js' {
  declare module.exports: $Exports<'parcel/src/assets/JSAsset'>;
}
declare module 'parcel/src/assets/JSONAsset.js' {
  declare module.exports: $Exports<'parcel/src/assets/JSONAsset'>;
}
declare module 'parcel/src/assets/LESSAsset.js' {
  declare module.exports: $Exports<'parcel/src/assets/LESSAsset'>;
}
declare module 'parcel/src/assets/PugAsset.js' {
  declare module.exports: $Exports<'parcel/src/assets/PugAsset'>;
}
declare module 'parcel/src/assets/RawAsset.js' {
  declare module.exports: $Exports<'parcel/src/assets/RawAsset'>;
}
declare module 'parcel/src/assets/ReasonAsset.js' {
  declare module.exports: $Exports<'parcel/src/assets/ReasonAsset'>;
}
declare module 'parcel/src/assets/RustAsset.js' {
  declare module.exports: $Exports<'parcel/src/assets/RustAsset'>;
}
declare module 'parcel/src/assets/SASSAsset.js' {
  declare module.exports: $Exports<'parcel/src/assets/SASSAsset'>;
}
declare module 'parcel/src/assets/StylusAsset.js' {
  declare module.exports: $Exports<'parcel/src/assets/StylusAsset'>;
}
declare module 'parcel/src/assets/TOMLAsset.js' {
  declare module.exports: $Exports<'parcel/src/assets/TOMLAsset'>;
}
declare module 'parcel/src/assets/TypeScriptAsset.js' {
  declare module.exports: $Exports<'parcel/src/assets/TypeScriptAsset'>;
}
declare module 'parcel/src/assets/VueAsset.js' {
  declare module.exports: $Exports<'parcel/src/assets/VueAsset'>;
}
declare module 'parcel/src/assets/WebManifestAsset.js' {
  declare module.exports: $Exports<'parcel/src/assets/WebManifestAsset'>;
}
declare module 'parcel/src/assets/YAMLAsset.js' {
  declare module.exports: $Exports<'parcel/src/assets/YAMLAsset'>;
}
declare module 'parcel/src/builtins/_empty.js' {
  declare module.exports: $Exports<'parcel/src/builtins/_empty'>;
}
declare module 'parcel/src/builtins/bundle-loader.js' {
  declare module.exports: $Exports<'parcel/src/builtins/bundle-loader'>;
}
declare module 'parcel/src/builtins/bundle-url.js' {
  declare module.exports: $Exports<'parcel/src/builtins/bundle-url'>;
}
declare module 'parcel/src/builtins/css-loader.js' {
  declare module.exports: $Exports<'parcel/src/builtins/css-loader'>;
}
declare module 'parcel/src/builtins/helpers.js' {
  declare module.exports: $Exports<'parcel/src/builtins/helpers'>;
}
declare module 'parcel/src/builtins/hmr-runtime.js' {
  declare module.exports: $Exports<'parcel/src/builtins/hmr-runtime'>;
}
declare module 'parcel/src/builtins/index.js' {
  declare module.exports: $Exports<'parcel/src/builtins/index'>;
}
declare module 'parcel/src/builtins/loaders/browser/css-loader.js' {
  declare module.exports: $Exports<'parcel/src/builtins/loaders/browser/css-loader'>;
}
declare module 'parcel/src/builtins/loaders/browser/js-loader.js' {
  declare module.exports: $Exports<'parcel/src/builtins/loaders/browser/js-loader'>;
}
declare module 'parcel/src/builtins/loaders/browser/wasm-loader.js' {
  declare module.exports: $Exports<'parcel/src/builtins/loaders/browser/wasm-loader'>;
}
declare module 'parcel/src/builtins/loaders/node/css-loader.js' {
  declare module.exports: $Exports<'parcel/src/builtins/loaders/node/css-loader'>;
}
declare module 'parcel/src/builtins/loaders/node/js-loader.js' {
  declare module.exports: $Exports<'parcel/src/builtins/loaders/node/js-loader'>;
}
declare module 'parcel/src/builtins/loaders/node/wasm-loader.js' {
  declare module.exports: $Exports<'parcel/src/builtins/loaders/node/wasm-loader'>;
}
declare module 'parcel/src/builtins/prelude.js' {
  declare module.exports: $Exports<'parcel/src/builtins/prelude'>;
}
declare module 'parcel/src/builtins/prelude.min.js' {
  declare module.exports: $Exports<'parcel/src/builtins/prelude.min'>;
}
declare module 'parcel/src/builtins/prelude2.js' {
  declare module.exports: $Exports<'parcel/src/builtins/prelude2'>;
}
declare module 'parcel/src/builtins/prelude2.min.js' {
  declare module.exports: $Exports<'parcel/src/builtins/prelude2.min'>;
}
declare module 'parcel/src/Bundle.js' {
  declare module.exports: $Exports<'parcel/src/Bundle'>;
}
declare module 'parcel/src/Bundler.js' {
  declare module.exports: $Exports<'parcel/src/Bundler'>;
}
declare module 'parcel/src/cli.js' {
  declare module.exports: $Exports<'parcel/src/cli'>;
}
declare module 'parcel/src/FSCache.js' {
  declare module.exports: $Exports<'parcel/src/FSCache'>;
}
declare module 'parcel/src/HMRServer.js' {
  declare module.exports: $Exports<'parcel/src/HMRServer'>;
}
declare module 'parcel/src/Logger.js' {
  declare module.exports: $Exports<'parcel/src/Logger'>;
}
declare module 'parcel/src/packagers/CSSPackager.js' {
  declare module.exports: $Exports<'parcel/src/packagers/CSSPackager'>;
}
declare module 'parcel/src/packagers/HTMLPackager.js' {
  declare module.exports: $Exports<'parcel/src/packagers/HTMLPackager'>;
}
declare module 'parcel/src/packagers/index.js' {
  declare module.exports: $Exports<'parcel/src/packagers/index'>;
}
declare module 'parcel/src/packagers/JSConcatPackager.js' {
  declare module.exports: $Exports<'parcel/src/packagers/JSConcatPackager'>;
}
declare module 'parcel/src/packagers/JSPackager.js' {
  declare module.exports: $Exports<'parcel/src/packagers/JSPackager'>;
}
declare module 'parcel/src/packagers/Packager.js' {
  declare module.exports: $Exports<'parcel/src/packagers/Packager'>;
}
declare module 'parcel/src/packagers/RawPackager.js' {
  declare module.exports: $Exports<'parcel/src/packagers/RawPackager'>;
}
declare module 'parcel/src/packagers/SourceMapPackager.js' {
  declare module.exports: $Exports<'parcel/src/packagers/SourceMapPackager'>;
}
declare module 'parcel/src/Parser.js' {
  declare module.exports: $Exports<'parcel/src/Parser'>;
}
declare module 'parcel/src/Pipeline.js' {
  declare module.exports: $Exports<'parcel/src/Pipeline'>;
}
declare module 'parcel/src/Resolver.js' {
  declare module.exports: $Exports<'parcel/src/Resolver'>;
}
declare module 'parcel/src/scope-hoisting/concat.js' {
  declare module.exports: $Exports<'parcel/src/scope-hoisting/concat'>;
}
declare module 'parcel/src/scope-hoisting/hoist.js' {
  declare module.exports: $Exports<'parcel/src/scope-hoisting/hoist'>;
}
declare module 'parcel/src/scope-hoisting/mangler.js' {
  declare module.exports: $Exports<'parcel/src/scope-hoisting/mangler'>;
}
declare module 'parcel/src/scope-hoisting/renamer.js' {
  declare module.exports: $Exports<'parcel/src/scope-hoisting/renamer'>;
}
declare module 'parcel/src/scope-hoisting/shake.js' {
  declare module.exports: $Exports<'parcel/src/scope-hoisting/shake'>;
}
declare module 'parcel/src/scope-hoisting/utils.js' {
  declare module.exports: $Exports<'parcel/src/scope-hoisting/utils'>;
}
declare module 'parcel/src/Server.js' {
  declare module.exports: $Exports<'parcel/src/Server'>;
}
declare module 'parcel/src/SourceMap.js' {
  declare module.exports: $Exports<'parcel/src/SourceMap'>;
}
declare module 'parcel/src/transforms/babel.js' {
  declare module.exports: $Exports<'parcel/src/transforms/babel'>;
}
declare module 'parcel/src/transforms/htmlnano.js' {
  declare module.exports: $Exports<'parcel/src/transforms/htmlnano'>;
}
declare module 'parcel/src/transforms/postcss.js' {
  declare module.exports: $Exports<'parcel/src/transforms/postcss'>;
}
declare module 'parcel/src/transforms/posthtml.js' {
  declare module.exports: $Exports<'parcel/src/transforms/posthtml'>;
}
declare module 'parcel/src/transforms/terser.js' {
  declare module.exports: $Exports<'parcel/src/transforms/terser'>;
}
declare module 'parcel/src/utils/bundleReport.js' {
  declare module.exports: $Exports<'parcel/src/utils/bundleReport'>;
}
declare module 'parcel/src/utils/config.js' {
  declare module.exports: $Exports<'parcel/src/utils/config'>;
}
declare module 'parcel/src/utils/customErrors.js' {
  declare module.exports: $Exports<'parcel/src/utils/customErrors'>;
}
declare module 'parcel/src/utils/emoji.js' {
  declare module.exports: $Exports<'parcel/src/utils/emoji'>;
}
declare module 'parcel/src/utils/env.js' {
  declare module.exports: $Exports<'parcel/src/utils/env'>;
}
declare module 'parcel/src/utils/fs.js' {
  declare module.exports: $Exports<'parcel/src/utils/fs'>;
}
declare module 'parcel/src/utils/generateCertificate.js' {
  declare module.exports: $Exports<'parcel/src/utils/generateCertificate'>;
}
declare module 'parcel/src/utils/getCertificate.js' {
  declare module.exports: $Exports<'parcel/src/utils/getCertificate'>;
}
declare module 'parcel/src/utils/getRootDir.js' {
  declare module.exports: $Exports<'parcel/src/utils/getRootDir'>;
}
declare module 'parcel/src/utils/getTargetEngines.js' {
  declare module.exports: $Exports<'parcel/src/utils/getTargetEngines'>;
}
declare module 'parcel/src/utils/installPackage.js' {
  declare module.exports: $Exports<'parcel/src/utils/installPackage'>;
}
declare module 'parcel/src/utils/is-url.js' {
  declare module.exports: $Exports<'parcel/src/utils/is-url'>;
}
declare module 'parcel/src/utils/lineCounter.js' {
  declare module.exports: $Exports<'parcel/src/utils/lineCounter'>;
}
declare module 'parcel/src/utils/loadPlugins.js' {
  declare module.exports: $Exports<'parcel/src/utils/loadPlugins'>;
}
declare module 'parcel/src/utils/localRequire.js' {
  declare module.exports: $Exports<'parcel/src/utils/localRequire'>;
}
declare module 'parcel/src/utils/md5.js' {
  declare module.exports: $Exports<'parcel/src/utils/md5'>;
}
declare module 'parcel/src/utils/objectHash.js' {
  declare module.exports: $Exports<'parcel/src/utils/objectHash'>;
}
declare module 'parcel/src/utils/openInBrowser.js' {
  declare module.exports: $Exports<'parcel/src/utils/openInBrowser'>;
}
declare module 'parcel/src/utils/parseCSSImport.js' {
  declare module.exports: $Exports<'parcel/src/utils/parseCSSImport'>;
}
declare module 'parcel/src/utils/pipeSpawn.js' {
  declare module.exports: $Exports<'parcel/src/utils/pipeSpawn'>;
}
declare module 'parcel/src/utils/prettifyTime.js' {
  declare module.exports: $Exports<'parcel/src/utils/prettifyTime'>;
}
declare module 'parcel/src/utils/prettyError.js' {
  declare module.exports: $Exports<'parcel/src/utils/prettyError'>;
}
declare module 'parcel/src/utils/PromiseQueue.js' {
  declare module.exports: $Exports<'parcel/src/utils/PromiseQueue'>;
}
declare module 'parcel/src/utils/promisify.js' {
  declare module.exports: $Exports<'parcel/src/utils/promisify'>;
}
declare module 'parcel/src/utils/serializeObject.js' {
  declare module.exports: $Exports<'parcel/src/utils/serializeObject'>;
}
declare module 'parcel/src/utils/syncPromise.js' {
  declare module.exports: $Exports<'parcel/src/utils/syncPromise'>;
}
declare module 'parcel/src/utils/urlJoin.js' {
  declare module.exports: $Exports<'parcel/src/utils/urlJoin'>;
}
declare module 'parcel/src/visitors/dependencies.js' {
  declare module.exports: $Exports<'parcel/src/visitors/dependencies'>;
}
declare module 'parcel/src/visitors/env.js' {
  declare module.exports: $Exports<'parcel/src/visitors/env'>;
}
declare module 'parcel/src/visitors/fs.js' {
  declare module.exports: $Exports<'parcel/src/visitors/fs'>;
}
declare module 'parcel/src/visitors/globals.js' {
  declare module.exports: $Exports<'parcel/src/visitors/globals'>;
}
declare module 'parcel/src/visitors/matches-pattern.js' {
  declare module.exports: $Exports<'parcel/src/visitors/matches-pattern'>;
}
declare module 'parcel/src/Watcher.js' {
  declare module.exports: $Exports<'parcel/src/Watcher'>;
}
declare module 'parcel/src/worker.js' {
  declare module.exports: $Exports<'parcel/src/worker'>;
}
declare module 'parcel/src/workerfarm/child.js' {
  declare module.exports: $Exports<'parcel/src/workerfarm/child'>;
}
declare module 'parcel/src/workerfarm/errorUtils.js' {
  declare module.exports: $Exports<'parcel/src/workerfarm/errorUtils'>;
}
declare module 'parcel/src/workerfarm/Worker.js' {
  declare module.exports: $Exports<'parcel/src/workerfarm/Worker'>;
}
declare module 'parcel/src/workerfarm/WorkerFarm.js' {
  declare module.exports: $Exports<'parcel/src/workerfarm/WorkerFarm'>;
}
