// flow-typed signature: 0b09a31754af9c00b5b5b282961811b4
// flow-typed version: <<STUB>>/structured-clone_v^0.2.2/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'structured-clone'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'structured-clone' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'structured-clone/clone' {
  declare module.exports: any;
}

declare module 'structured-clone/serialize' {
  declare module.exports: any;
}

declare module 'structured-clone/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'structured-clone/clone.js' {
  declare module.exports: $Exports<'structured-clone/clone'>;
}
declare module 'structured-clone/index' {
  declare module.exports: $Exports<'structured-clone'>;
}
declare module 'structured-clone/index.js' {
  declare module.exports: $Exports<'structured-clone'>;
}
declare module 'structured-clone/serialize.js' {
  declare module.exports: $Exports<'structured-clone/serialize'>;
}
declare module 'structured-clone/test/test.js' {
  declare module.exports: $Exports<'structured-clone/test/test'>;
}
